export const LOGIN_API = '/auth/login'
export const REGISTER_API = '/auth/signup'
export const CHANGE_PASSWORD = '/auth/change_password'
export const REFREST_TOKEN = '/auth/refresh'
export const LOGOUT_API = '/auth/logout'
export const USER_PERMISSIONS = '/auth/user-permissions'

export const PRODUCT = '/pal-api/product'
export const PRODUCTS = '/pal-api/products'
export const CONFIG = '/pal-api/configs'
