export const LOGIN_API = '/login'
export const REGISTER_API = '/signup'
export const CHANGE_PASSWORD = '/change_password'
export const REFREST_TOKEN = '/refresh'
export const LOGOUT_API = '/logout'
export const USER_PERMISSIONS = '/user-permissions'

export const PRODUCT = '/product'
export const PRODUCTS = '/products'
export const CONFIG = '/configs'
